version: "3.7"
services: 
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    image: rabbitmq:3-management-alpine

  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: ./emergency-web-client/Dockerfile
    volumes:
      - './emergency-web-client:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
      
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  client:
    container_name: client
    ports: 
      - 5000:80
    build: 
      context: .
      dockerfile: ./Restpirators.Client/Dockerfile
    restart: on-failure
    depends_on: 
      - rabbitmq

  dispatcher:
    container_name: dispatcher
    ports: 
      - 5001:80
    build: 
      context: .
      dockerfile: ./Restpirators.Dispatcher/Dockerfile
    restart: on-failure
    depends_on: 
      - rabbitmq

  analyzer:
    container_name: analyzer
    ports: 
      - 5002:80
    build:
      context: .
      dockerfile: ./Restpirators.Analyzer/Dockerfile
    restart: on-failure
    depends_on: 
      - rabbitmq
      - mongodb

  auth:
    container_name: auth
    ports: 
      - 5004:80
    build:
      context: .
      dockerfile: ./Restpirators.Auth/Dockerfile
    restart: on-failure
    depends_on: 
      - rabbitmq

  gateway:
    container_name: gateway
    ports: 
      - 5003:80
    build:
      context: .
      dockerfile: ./Restpirators.Gateway/Dockerfile
    depends_on: 
      - client
      - dispatcher
      - analyzer
      - auth

  elasticsearch:  
    container_name: elasticsearch  
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1  
    ports:  
      - 9200:9200  
    volumes:  
      - elasticsearch-data:/usr/share/elasticsearch/data  
    environment:  
      - xpack.monitoring.enabled=true  
      - xpack.watcher.enabled=false  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
      - discovery.type=single-node  
    networks:  
      - elastic  
  
  kibana:  
   container_name: kibana  
   image: docker.elastic.co/kibana/kibana:7.9.1  
   ports:  
    - 5601:5601  
   depends_on:  
    - elasticsearch  
   environment:  
    - ELASTICSEARCH_URL=http://localhost:9200  
   networks:  
    - elastic  
    
networks:  
  elastic:  
    driver: bridge  
  
volumes:  
  elasticsearch-data:  
  