version: "3.7"
services: 
  rabbitmq:
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    image: rabbitmq:3-management-alpine

  client:
    container_name: client
    ports: 
      # - 4000:80
      - 4001:443
      - 44333:80
    # environment: 
    build: 
      context: .
      dockerfile: ./Restpirators.Client/Dockerfile
    restart: on-failure
    depends_on: 
      - rabbitmq

  dispatcher:
    container_name: dispatcher
    ports: 
      - 5000:80
      - 5001:443
    # environment: 
    build: 
      context: .
      dockerfile: ./Restpirators.Dispatcher/Dockerfile
    # restart: on-failure
    depends_on: 
      - rabbitmq

  analyzer:
    container_name: analyzer
    ports: 
      - 6000:80
      - 6001:443
    build:
      context: .
      dockerfile: ./Restpirators.Analyzer/Dockerfile
    depends_on: 
      - rabbitmq

  gateway:
    container_name: gateway
    ports: 
      - 44315:80
      # - 7000:80
      - 7001:443
    build:
      context: .
      dockerfile: ./Restpirators.Gateway/Dockerfile
    depends_on: 
      - client
     

  